# coding: utf-8

# ryu->mld
CON_SWITCH_FEATURE = 11
CON_PACKET_IN = 12

# mld->ryu
CON_FLOW_MOD = 21
CON_PACKET_OUT = 22

# MLD処理部でのReport受信後の動作
CON_REPLY_NOTHING = 0
CON_REPLY_ADD_FLOW_MOD = 11
CON_REPLY_ADD_FLOW_MOD_AND_PACKET_OUT = 12
CON_REPLY_DEL_FLOW_MOD = 21
CON_REPLY_DEL_FLOW_MOD_AND_PACKET_OUT = 22
